apiVersion: v1
kind: Service
metadata:
  name: eval
  namespace: chronon
spec:
  selector:
    app: eval
  ports:
    - port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eval
  namespace: chronon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eval
  template:
    metadata:
      labels:
        app: eval
    spec:
      containers:
        - name: eval
          image: chronon-spark-k8s:latest
          ports:
            - containerPort: 9090
          env:
            - name: HUB_URL
              value: "http://hub:8080"
