apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: chronon
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "persistentvolumeclaims"]
    verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: chronon
roleRef:
  kind: ClusterRole
  name: spark
  apiGroup: rbac.authorization.k8s.io
